# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 20:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='match date')),
                ('victory', models.CharField(blank=True, choices=[(b'a', 'Team A'), (b'b', 'Team B')], max_length=1, null=True, verbose_name='victory')),
                ('team_a_players', models.ManyToManyField(related_name='team_a_players', to='players.Player')),
                ('team_a_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a_team', to='players.Team')),
                ('team_b_players', models.ManyToManyField(related_name='team_b_players', to='players.Player')),
                ('team_b_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b_team', to='players.Team')),
            ],
            options={
                'verbose_name': 'match',
                'verbose_name_plural': 'matchs',
            },
        ),
    ]
